Promact/oauth-server

- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Shared/_Layout.cshtml
Solved bug related to text appearing on login page
> Solved bug related to text appearing on top

- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/tsconfig.json
- deploy.cmd
Fixed all the issues with typescript compilation and moving production files.
> Deploy script updated

- SETUP.md
Listed out all environment and appsettings variable for setting up application on any new server.
> created SETUP.md

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/IProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.development.example.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.json
Updated UserRepository and Project Controller
> Task mail report

- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumerapp-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.html
updated multi selection drop down in project module.
> Updated Project Module for the multi selection drop down

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ConsumerAppController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.development.example.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.module.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/index.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/loader.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
completed Re-send Functionality
> Re-Send Functionality

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/project/mock.project.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.routes.ts
Added loader in Project Module and User List Page.
> Tab switching issues

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
completd bugs #57 ,#56 ,#55 ,#53
> Solve user related bugs and support

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
I have updated project-list.component.ts.
> Tab Switching issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/AccountController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/IEmailSender.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.development.example.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
I have use exceptions, for check what is throwing the actual error.
> Re send mail issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/NLog.config
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
Added Nlog
update  UserController.cs and User Repository.cs and also MessageService.cs
> Added NLog

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.ts
This Pull Request for check email template path exists or not
> Pull Request For Email Template Path Related Issue 

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.model.ts
solved the issue number #72  (In "View Project" list of team members are not fully seen).
> Project view issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
update MssageServices.cs and AppSetting.cs
> Update SSL settings in Mail

- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/NLog.config
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/gulpfile.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/karma-test-shim.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/karma.conf.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/mock.routerLink.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/project/mock.project.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/shared.module.ts
I have updated karma.config and karma-test-shim files.
> Updated Karma.config and karma-test-shim files

- Promact.Oauth.Server/src/Promact.Oauth.Server/gulpfile.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add-component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumerapp-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/consumerapp/mock.consumerapp.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/user/mock.user.service.ts
update Consumer app and change-password and also project view test case, update consumer module spec file and change password spec file, update mock.user.service.ts and mock.consumerapp.service.ts and also update project.json
> Request For Consumer Module Test Case and Change Password

- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/OAuthRepository/OAuthRepository.cs
SlackUserName not available at Slack project after user login issue resolved
> SlackUserName included in returnUrl

- .travis.yml
- Promact.Oauth.Server/global.json
- deploy.cmd
> Updated package manager to yarn and updated .net tools target to 3133

- Promact.Oauth.Server/src/Promact.Oauth.Server/karma.conf.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/mock.activatedroute.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/mock.login.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/mock.router.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/user/mock.user.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.ts
Fixed issue #40 updated user test cases
> Updated user module test cases

- .travis.yml
- Promact.Oauth.Server/src/Promact.Oauth.Server/NLog.config
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ConsumerAppRepository/ConsumerAppRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/GlobalExceptionFilter.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/karma.conf.js
Issue #74 
Files Changed:
ConsumerAppRepository.cs - Remove Try Catch from repository
GlobalExceptionFilter.cs  - Added File For Gloabl Exception class file for logged to global exception
Startup.cs - Configure GlobalExceptionFilter in Startup.cs (Added Services)
> Added global exception filter For Logger

- Promact.Oauth.Server/src/Promact.Oauth.Server/karma.conf.js
- README.md
Issue #16
Changed File:
1) Travis.Yml : Update Cat Command for generating coverage report in coveralls
2) Karma.conf.js :  Remove extra code.
> Client Side Coveralls

- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
Fix Issue #103. I have updated Project Repository now Created date and Updated date format are same.
> Project module time issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettingUtil.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/SendGridEmailSender.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.development.example.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
Implemented Sendgrid WebAPI as per issue #96
 
**Files Changed:**
**StringConstant.cs** – Added string constants.
**AppSettingUtil.cs**  - Removed unnecessary usings.
**AppSettings.cs**  - Added SendGridApi property
**UserRepository.cs**  - Uncommented SendMail method and removed logging.
**appsettings.development.example.json**  - Added SendGridApi example.
**project.json**  - Added package SendGrid.NetCore
**SendGridEmailSender.cs** - Implementation added for sending mail in production.
**StartUP.cs** - Added resolving implementation of IEmailSender based on environment(development or production)
> SendGrid WebApi implementation for sending mail in production environment

- .travis.yml
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/BaseProvider.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ConsumerAppRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/OAuthRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ProjectTests.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/IStringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/AccountController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/OAuthController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Exception Handler/SlackUserNotFound.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettingUtil.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ConsumerAppRepository/ConsumerAppRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/OAuthRepository/OAuthRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/SendGridEmailSender.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.development.example.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.service.ts
Fixes #91 
Changes Properties in this request:
**User Repository :** Changed in FindUserBySlackUserName Method, changed return values.
**user-add.component.ts :** added one condtion for check slack user name is already exists and also optimize some code. 
**user-add-html :** update desinging related changes. 
**User Controller :** change method name 
**Travis.yml:** Update Travis.Yml File For Solve Merging issue
> Add user not working

- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/SendGridEmailSender.cs
IStringConstant injected.
**File changed** is :
1. **SendGridEmailSender.cs** - IStringConstant injected.
> StringConstant injected properly

- .travis.yml
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/IStringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/AccountController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Exception Handler/SlackUserNotFound.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/SendGridEmailSender.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.service.ts
Updated Project Repository as per issue #119 
Files Changed:
ProjectRepository.cs : Updated GetById Mehod.
> View project issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/SendGridEmailSender.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Template/ForgotPassword.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/Template/UserDetial.html
Email content is now in proper Html format. Fixed issue #124 
**Files changed** are :
1. **SendGridEmailSender.cs** - Changed the message rendering type to Html.
2. **UserDetial.html** - Changed format of email content.
3. **ForgotPassword.html** - Changed format of email content.
> Email Content Format Changed

- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/OAuthRepository/OAuthRepository.cs
Fixes #125 
Changed Files :
OAuthRepository.cs : Update OAuthClientChecking  Method (GetAppDetails method is asynchronous so I have added Result for wait to response)
> External Login Issue 

- deploy.cmd
updated deploy.cmd to fixed issue #114 
files change
deploy.cmd - removed  MSBUILD_PATH command and Added dotnet restore , dotnet build
and dotnet publish commands
> Build time issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.ts
Fixes #92 
Changed Files:
user-details.component.ts : I have set boolean variable admin as true in construtor
UserRepository.cs = changed after rebase
> User details page issue 

- deploy.cmd
Reverts Promact/promact-oauth-server#129
> Revert "Build time issue"

- deploy.cmd
Fixed #114 
File change is
deploy.cmd : removed MSBUILD_PATH and added dotnet restore , build and publish commands.
> updated deploy.cmd

- .travis.yml
- Promact.Oauth.Server/src/Promact.Oauth.Server/gulpfile.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/tslint.json
- deploy.cmd
Fixes #113 
Changed Files:
gulpfile.js : added new task for tslint
package.json: added new packages for tslint
tslint.json : added tslint.json to define rules.
travis.yml : added command to run 'tslint'
> Implement tslint

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/HomeController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/UserRoleAc.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/SendGridEmailSender.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.development.example.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/karma-test-shim.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.module.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/index.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/userrole.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.component.ts
Fixes #149
Changed Files Are
1) User-add.component.ts - trim firstname in adduser method
2) User-Edit.component.ts :- trim firstname in edituser method
> RemoveSpacingFromUserName 

- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/SendGridEmailSender.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/user/mock.user.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.html
Fixed #138 
Changed File: 
1.**AppSettings.cs** : changed send grid api key same as appseting.json
2.**SendGridEmailSender.cs**:changed sendgrid api key property  name
3.**user-add.component.ts**:changed error message.
4.**user-add.html**:remove * from feild name
5.**mock.user.service.ts**: update user add mock service
6.**user-add.component.spec.ts**:added new test case
> Email field is not working proper

- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
GertUser naming convention changed. Fixed #140
**File changed** :
1. **UserRepository.cs** - Naming convention improved in GetUser method of UserRepository.cs
> GetUser naming convention changed.

- Promact.Oauth.Server/global.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/mock.base.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/project/mock.project.service.ts
Fixed #161 
Changed Files:
project-add.component.spec.ts - use let instead of var , rename projectModel to ProjectModel  
project-add.component.ts - add implements OnInit , rename projectModel to ProjectModel  
project-edit.component.spec.ts - use let instead of var , rename projectModel to ProjectModel
project-edit.component.ts - use let instead of var , rename projectModel to ProjectModel
project-list.component.spec.ts - rename projectModel to ProjectModel
project-list.component.ts - add implements OnInit , rename projectModel to ProjectModel
project-view.component.spec.ts - use let instead of var , rename projectModel to ProjectModel
project-view.component.ts - rename projectModel to ProjectModel
project.component.ts - implements OnInit
project.model.ts - rename projectModel to …
> Tslint issue project module

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ConsumerAppRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ConsumerAppController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Exception Handler/ConsumerAppNameIsAlreadyExists.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Exception Handler/ConsumerAppNotFound.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Exception Handler/FailedToFetchDataException.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ConsumerAppRepository/ConsumerAppRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ConsumerAppRepository/IConsumerAppRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add-component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/consumerapp/mock.consumerapp.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/mock.base.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/project/mock.project.service.ts
Fixed #152 
Changed Files:
1.**ConsumerAppRepositoryTest.cs**: update naming conventions 
2.**ConsumerAppController.cs**: update api route path
3.**ConsumerAppNotFound.cs**:add customer exception class
4.**IConsumerAppRepository.cs**:update naming conventions
5.**consumerapp.service.ts**:update services rateled api route path
> Stream line code of consumer model

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/OAuthApplication.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationUser.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/OAuthRepository/OAuthRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Seed/EnsureSeedData.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.service.ts
Fixes Promact/slack-erp-custom-integration-mvc#100.
**Files changed are:** 
**1. UserRepositoryTest.cs** – Test case updated. SlackUserId changed to SlackUserName.
**2. UserController.cs** - SlackUserId changed to SlackUserName.
**3. OAuthApplication.cs** – UserId added.
**4. ApplicationUser.cs** - SlackUserName added.
**5. OAuthRepository.cs** – SlackUserName checked during external login and SlackUerId added to database.
**6. IUserRepository.cs** – Method name changed.
**7. UserRepository.cs** -  SlackUserId replaced by SlackUserName.
**8. EnsureSeedData.cs** – SlackUserName added.
**9. user-add.component.ts**  -  SlackUserId replaced by SlackUserName.
**10. user-add.html** - SlackUserId replaced by SlackUserName.
**11. user-edit.html** – Editable SlackUserName added.
**12. …
> SLackUserId fetched and stored at external login time.

- Promact.Oauth.Server/global.json
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ProjectTests.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Data Repository/DataRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/OAuthRepository/OAuthRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/IProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.service.ts
Fixed #141
Files Changed:
ProjectTests.cs Updated GetProjectUserByGroupName Method
ProjectController.cs : Updated comments , Proper naming conventions and Implement proper exception handling
DataRepository.cs : Added FetchAsync Method
IDataRepository.cs : Added FetchAsync Method
ProjectNotFound.cs : Added ProjectNotFound.cs
UserRoleNotFound.cs: Added UserRoleNotFound.cs
IProjectRepository.cs: Updated AddUserProject and GetProjectUserByGroupName Method
ProjectRepository.cs :  Updated comments , Proper naming conventions and Implement proper exception handling
project.service.ts : Updated RESTful API URLs
> Refactor project controller

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
Fixes#141 and Promact/slack-erp-custom-integration-mvc#90.
**File changed:**
**1. UserController.cs** - Parameter name changed to match that of route.
**2. UserRepository.cs** - Null condition checked.
> Parameter name changed to that of Route. 

- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.routes.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/userrole.model.ts
Fixed #126 
Files Changed:
ProjectRepository.cs - Updated GetAllProjectForUserAsync method.
user-details.html - Added condition when user are admin then show back button 
user-edit.component.ts - updated route path.
> Error while switching tab

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ConsumerAppRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/IStringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/AppSettings.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Services/MessageServices.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/appsettings.development.example.json
Fixed #185 
Changed Files
1.*ConsumerAppRepositoryTest.cs* : update all test cases
> Update Test Cases For Consumer App Module

- .travis.yml
Fixed  #190
Changed Files: 
1) **.travis.yml** : updated yarn integration (Used Caching with Yarn)
> Update yarn Integration For Travis

- .travis.yml
- Promact.Oauth.Server/global.json
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
Fixed #202 
File Changed: 
1) project.json : updated dotnet core version and all other dependencies.
2) travis.yml: updated dotnet version
3) global.json: corrected sdk version
> Upgrade project to latest DotNetCore 1.1 and all other dependencies

- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Shared/_Layout.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Shared/_ValidationScriptsPartial.cshtml
Fixed #210
Changed Files : 
1. **Index.cshtml** :  3rd party libraries are loaded from application root itself if environment is development otherwise loaded from CDN
2.**_Layout.cshtml**: Removed unnecessary scripts and style and also added above condition
3.**_ValidationScriptsPartial.cshtml**:Added Comments
> Load3rd party libraries over cdn

- Dockerfile
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/Program.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
- entrypoint.sh
Integrated custom promact image which allows faster build on docker. Fixed Nlog integration.
> Docker integration

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumerapp-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp.html
Fixes - #228 
**1. consumerapp-add.html** - fixed validator issue
**2. consumer-edit.component.ts** - update edit method
**3. consumer-edit.component.spec.ts** - update edit test case
> Fixed validator issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.module.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add-component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumerapp-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/stringconstant.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.spec.ts
Fixed #181
**removed common http services by @ankit213 in issue #200 .**
Files Changed:
1) AppComponent.ts - Added String Constant and removed unnecessary declaration 
2) AppComponent.spec.ts - Added String Constant and removed unnecessary declaration 
3) project-add.component.spec.ts - Added String Constant and removed unnecessary declaration 
4) project-edit.component.spec.ts - Added String Constant and removed unnecessary declaration 
5) project-edit.component.spec.ts - Added String Constant
6) project-list.component.ts - Added String Constant and removed unnecessary declaration 
7) project-list.component.spec.ts - Added String Constant and removed unnecessary declaration 
8) project-view.component.spec.ts - Added String Constant and removed unnecessary declaration 
9) …
> Added String Constant and removed unnecessary declaration

- .travis.yml
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/karma.conf.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.spec.ts
- README.md
- appveyor.yml
- codecov.yml
Fixed #213
Changed File: 
1. **travis.yml** : removed client side coveralls command and enviorment variable.
2. **Promact.Oauth.Server.Tests/project.json**: added xunit.runner.console package.
3. **karma.conf.js** : updated karma.config for codecov (updated reporters type).
3. **package.json** : added codecov.io package.
4. **Promact.Oauth.Server/project.json** : added  "coveralls.net": ""OpenCover" packages.
5. **README.md** : added badge for codecov
6. **appveyor.yml**: added appveyor.yml
> Codecov for client side and coveralls for server side

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add-component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumerapp-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumerapp-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/url.validator.ts
Fixes - some issue of validation message
**1. consumerapp-add.html** - added proper message for url validation and set scope as required field
**2. consumerapp-edit.html** - added proper message for url validation and set scope as required field
**3. consumerapp.service.ts** - updated updateConsumerApps 
**4. url.validator.ts** - updated validation return value
**5. consumerapp-add.component.ts** - added method to keep scope field required
**6. consumerapp-edit.component.ts** - added method to keep scope field required
**7. consumerapp-add-component.spec.ts** - add test cases for scope validator method
**8. consumerapp-edit-component.spec.ts** - add test cases for scope validator method
> Update consumer app

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
Fixes - Issue of ExecuteDbDataReaderAsync
**1. UserControllercs** - updated api doc
**2. UserRepository.cs** - updated ListOfTeamLeaderByUserIdAsync
> Fixes - Issue of ExecuteDbDataReaderAsync occured by ListOfTeamLeaderByUserIdAsync

- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
Fixed #251 
Files Changed:
1.**Startup.cs** : updated startup.cs file (updated nLog Configure)
> NLog is not creating log file 

- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
X-Forwarded header added in Startup class to solve the issue of Authentication against Production OAuth Server
> Added X-Forwared header in startup class in order to resolve the issue

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ConsumerAppController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ConsumerAppRepository/ConsumerAppRepository.cs
Fixes - Added logger in update consumer
**1. ConsumerAppController.cs** - added logger debug and error and implement try catch with generic exception to get what the issue in live (added generic exception for testing purpose. I will remove it once problem - #256 is solved). 
**2. ConsumerAppRepository.cs** - used SaveAsync
> Added logger in update consumerApp

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ConsumerAppController.cs
Fixes - Issue of Dependency resolving 
**1. ConsumerAppController.cs** - resolve the Issue - Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger
> Fixes - Issue of Dependency resolving 

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ConsumerAppRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ConsumerAppController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ConsumerAppRepository/ConsumerAppRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ConsumerAppRepository/IConsumerAppRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp.service.ts
Fixes - #256 
**1. ConsumerAppController.cs** - removed unnecessary return in update and add method
**2. ConsumerAppRepository.cs** -removed unnecessary return in update and add method and updated xml comment
**3. IConsumerAppRepository.cs** - updated xml comment
**4. consumerapp.service.ts** - removed unnecessary return expected in update and add method
**5. ConsumerAppRepositoryTest.cs** - updated test cases
> Fixes - Issue #256

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ProjectTests.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
Fixes #267 
**Files changed are :**
**1. ProjectTests.cs -** Removed test case GetProjectByGroupNameException.
**2. ProjectController.cs -** Removed try catch.
**3. ProjectRepository.cs -** Removed ProjectNotFound Custom Exception from GetProjectBySlackChannelNameAsync.
> Removed ProjectNotFound Custom Exception from GetProjectBySlackChannelNameAsync.

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.module.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/authentication.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-routes.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.routes.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.routes.ts
Fixed #264
Files Changed
1.**app.module.ts** :  updated app.module.ts(added authenticationService in provider).
2.**authentication.service.ts** : added authentication.service.ts file(check login user role if login user role is admin, he will access all pages other wise display toast message "You are not authorized to view this page").
3.**consumerapp-routes.ts**: updated consumerapp-routes file for authentication.
4.**project.routes.ts**: updated project.routes.ts file for authentication.
5.**user.routes.ts**: updated user.routes.ts file for authentication.
> Implement Client Side Authentication

- README.md
- appveyor.yml
File Changed:
1.**appveyor.yml** : update appveyor.yml
> update Serverside Code Covrage

- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/karma.conf.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/index.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
- appveyor.yml
Fixed #271 
**File changes:**
1. **Index.cshtml**- Added the CDN for fonts .
2. **Consumerapp-add.html** - Changes in layout of the html.
3. **Project-add.html** -added icons in action column and width changes.
4. **project-list.html** -  Changes in html
5. **app-seagreen.css** - Styles applied for the new changes in design.
6  **index.html-** added icons for side menu
> Design changes in promact ouath.

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/karma.conf.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/project.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-add/consumerapp-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/index.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
- appveyor.yml
Fixes #272 
1. UserRepositoryTest - Added test cases of UserRepository to increase code coverage.
> Increased UserRepository code coverage

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/IProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- README.md
Fixes - Added new API for Erp-Issue - 215
1. ProjectController.cs - added new API to get list of project in with user is enrolled
2. IProjectRepository.cs - added new method to get list of project in with user is enrolled
3. ProjectRepository.cs - added new method to get list of project in with user is enrolled
> Added new API for Erp-Issue - #215

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ProjectTests.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/mock.location.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/stringconstant.ts
**Fixed #273** 
**Filed changed**
**ProjectTests.cs** - Added new test cases
**project-add.component.spec.ts** - Added new test cases
**project-add.component.ts** - Improved nameing convestion 
**project-edit.component.spec.ts** - Added new test cases
**project-view.component.spec.ts** - Added new test cases
**project-list.component.spec.ts** - Added new test cases
**project.component.spec.ts** - Added new test cases
**stringconstant.ts** - Added string constant
**mock.location** - Added new mock file
> Issue #273

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/app.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/error.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/user/mock.user.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/stringconstant.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.component.spec.ts
- README.md
Fixes #277 
**Files changed are:**
**1. app.component.spec.ts** - Added test case.
**2. error.model.ts** - Added model.
**3. mock.user.service.ts** - Added and updated mock ups.
**4. stringconstant.ts** - Added string constants.
**5. user-add.component.spec.ts** - Added and updated test cases.
**6. user-details.component.spec.ts** - Added test cases.
**7. user-edit.component.spec.ts** - Added test cases.
**8. user-list.component.spec.ts** - Added and updated test cases.
**9. user.component.spec.ts** - Added and updated test cases.
> Increase user module client side code coverage

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/error.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/user/mock.user.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/stringconstant.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-edit/user-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.spec.ts
Fixes #283 
**Files changed are:**
**1. change-password.component.spec.ts** - Added and updated test cases.
**2. mock.user.service.ts** - Updated mock up.
**3. stringconstant.ts** - Added string constants.
> Updated change password client side test case.

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
**File Changed** 
**project-add.component.spec.ts** - added test cases
**project-edit.component.spec.ts** - added test cases
**project-view.component.spec.ts** - added test cases
**project-list.component.spec.ts** - added test cases
**project-list.component..ts** - updated code.
> Added test cases for exception

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ProjectTests.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/IProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp.component.spec.ts
Fixes - ERP-API-215
**1. ProjectController.cs** - added new API GetListOfTeamMemberByProjectIdAsync
**2. IProjectRepository.cs** - added new method GetListOfTeamMemberByProjectIdAsync
**3. ProjectRepository.cs** - added new method GetListOfTeamMemberByProjectIdAsync
**4. ProjectTests.cs** - added test cases for GetListOfProjectsEnrollmentOfUserByUserIdAsync and GetListOfTeamMemberByProjectIdAsync
**5. consumerapp.component.spec.ts** - added spec for consumerapp.component.ts
> Added API for mail setting

- README.md
- appveyor.yml
Fixes - #289 
**1. README.md** - added table structure for view of build and coverage report
> Updated README.md

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/UserDetailAC.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/UserEmailListAc.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
Fixed #288 
1. **UserRepositoryTest.cs** : added new test cases for dynamic group
2. **UserController.cs**: added new API for get active user eamil list.
3. **UserEmailListAc.cs**: added new domain model application class
4. **UserRepository.cs**: added new methods for get active user email list.
5. **IUserRepository.cs** added new methods for get active user email list.
> Add api for dynamic groups

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
Fixes - Refactor of external api
1. UserController.cs - refactor API and doc
2. ProjectController.cs - refactor API and doc
> Refactor of external api

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/IStringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
Fixes - #296 
**1. UserController.cs** - updated the route url and api doc 
**2. UserRepository.cs** - updated the exception from SlackUserNotFound to UserNotFound
**3. IStringConstant.cs** - updated the name of varibale
**4. StringConstant.cs** - updated the name of varibale
**5. UserRepositoryTest.cs** - updated the test cases
> UserController.cs - updated the route url and api doc

- .travis.yml
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
Fixed #299
Files Changed: 
1.**travis.yml** : added bundlig command
2.**Index.cshtml**: added bundle file path
3.**package.json**: added script command for bundle
> Add bundling

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
**1. UserController.cs** - updated naming of variable
**2. UserRepository.cs** - removed unneccesary code of GetUserAsync
> Update because change in ERP - #259

- .travis.yml
- Dockerfile
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
1.**travis.yml** : updated codecov command name
2.**Dockerfile**: added new command for bundling
3.**package.json**: updated codecov command name
> update dockerfile and travis.yml also package.json file

- .travis.yml
- Dockerfile
Files Changed :
1.**Dockerfile** : updated docker file command
> update Docker Command For Bundling

- Promact.Oauth.Server/src/Promact.Oauth.Server/gulpfile.js
Files Changed 
1. **gulpfile.js** : updated gulpfile(added bundle task in  before build section)
> updated gulp file

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/ProjectTests.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/IStringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/ProjectController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/ProjectAc.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/Project.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/NLog.config
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/GlobalExceptionFilter.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/IProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-edit/project-edit.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-view/project-view.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project.model.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/mocks/project/mock.project.service.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/shared/stringconstant.ts
Fixes #290 
**Files changed are:**
**1. ProjectController.cs** - Added GetProjectByProjectIdAsync api and updated api doc.
**2. IProjectRepository.cs** -  Added GetProjectByProjectIdAsync.
**3. ProjectRepository.cs** - Implemented GetProjectByProjectIdAsync and updated GetListOfProjectsEnrollmentOfUserByUserIdAsync.
> Added new api to fetch project details using project id

- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/UserRepositoryTest.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/UserDetailWithProjectList.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/UserDetailWithProjectListAc.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/IUserRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/UserRepository/UserRepository.cs
Fixed #297 
**1. UserController.cs** : Added New API Method (GetUserDetailWithProjectListByUserId).
**2. UserDetailWithProjectListAc.cs** : Added new application class
**3. IUserRepository.cs** : Added new method for get user details with assigned projects 
**4. UserRepository.cs** : Added  new method for get user details with assigned projects
> Implement an API to fetch user details along with projects

- Promact.Oauth.Server/src/Promact.Oauth.Server/Template/UserDetail.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Consent/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Consent/_ScopeListItem.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
Fixed #307 
Files changed:
1. Index.cs html - html markup changes
2. _ScopeListItem.cshtml - html markup changes
3. app-seagreen.css - Styles applied for new markup
> Issue #307

- Promact.Oauth.Server/src/Promact.Oauth.Server/Template/UserDetail.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.html
Fixed #311
1. **change-password.component.spec.ts** : update test case 
2. **change-password.component.ts**: update change password cancel button method
3. **change-password.html**: added If condition in form tag for reset form.
> solved Issue #311

- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Models/ApplicationClasses/UserAC.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.spec.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.model.ts
Fixed #310 
Files changed are
UserController.cs - updated add use method
UserAC.cs - added joindate
user-add.component.spec.ts - added joindate
user-add.component.ts - added joindate and DatePipe 
user.model.ts - added joindate
> issue- #310.

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-details/user-details.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user.routes.ts
Fixed #315
Files changed : 
1. **user-details.html** :  removed commented code.
2. **user.routes.ts** : updated user route (removed AuthenticationService from edit user)
> solved Issue#315

- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/IStringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Constants/StringConstant.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Controllers/UserController.cs
1. **IStringConstant.cs** : Added new string constant for date fromat
2. **StringConstant.cs** : Added new string constant for date fromat
3. **UserController.cs** : Update date formate for joining date
> Update date format for joining date

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
Fixed #319 
Files Changed :
1. consumerapp-list.html : update consumerapp-list.html file 
2. app-seagreen.css : update app-seagreen.css file , added css in app-seagreen.css
> solved Issue #319

- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.html
**Fixed** #318
**file changed is**
**project-list.html** - added message.
> sloved no records to display issue 

- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Account/Login.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Account/ResetPasswordConfirmation.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/css/app-seagreen.css
Fixes #322 
Files changed:
ResetPasswordConfirmation.cshtml- html mark up changes
Login.cshtml - html mark up changes
app-seagreen.css- styles applied for html changes
> Resetpassword design 

- .travis.yml
- Dockerfile
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/gulpfile.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/rollup-config.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/tsconfig-aot.json
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/change-password/change-password.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-edit/consumer-edit.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/consumerapp/consumerapp-list/consumerapp-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-list/project-list.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.component.ts
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-list/user-list.component.ts
Fixes - #143 
**1. Index.html** - added script of build.js instead of bundle.js
**2. gulpfile.js** - added gulp task for aot and rollup
**3. package.json** - added script of aot and rollup && added packages - "@angular/compiler-cli": "~2.1.1",
"@angular/platform-server": "~2.1.1",
"gulp-ngc": "0.1.3",
"rollup-stream": "1.19.0",
"rollup": "^0.41.6",
"rollup-plugin-commonjs": "^8.0.2",
"rollup-plugin-node-resolve": "^3.0.0",
"rollup-plugin-uglify": "^1.0.1"
**4. rollup-config.js** - This config file tells Rollup that the app entry point is src/app/main.js . The dest attribute tells Rollup to create a bundle called build.js
**5. tsconfig-aot.json** - configuration for aot
**6. change-password.component.ts** - removed code smell caught by rollup
**7. consumer-edit.component.ts** - removed …
> Implemented server side compilation for angular 2

- Dockerfile
- Promact.Oauth.Server/src/Promact.Oauth.Server.Tests/Promact.Oauth.Server.Tests.csproj
- Promact.Oauth.Server/src/Promact.Oauth.Server/AutoMapper/AutoMapperProfileConfiguration.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Promact.Oauth.Server.csproj
- Promact.Oauth.Server/src/Promact.Oauth.Server/Startup.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/Views/Home/Index.cshtml
- Promact.Oauth.Server/src/Promact.Oauth.Server/gulpfile.js
Fixes - #326 
**1. AutoMapperProfileConfiguration.cs** - changes as per breaking changes in automapper
2**. Index.html** - removed build.js with bundle.js
**3. gulpfile.js** - added bundle command and removed aot and rollup command
**4. Startup.cs** - removed build warning
**5. Dockerfile** - added bundle command and removed aot and rollup command
**6. packages updated** - 
a. IdentityServer4.EntityFramework - 1.0.0 to 1.0.1
b. IdentityServer4 - 1.0.2 to 1.5.0
c. IdentityServer4.AspNetIdentity - 1.0.0 to 1.0.1
d. IdentityServer4.AccessTokenValidation - 1.0.2 to 1.1.0
e. AutoMapper - 5.2.0 to 6.0.2
**7. packages updated (Test)** - 
a. IdentityServer4.EntityFramework - removed
b. IdentityServer4 - (removed)
c. IdentityServer4.AspNetIdentity - (removed)
d. …
> Updated IdentityServer dependency to latest

- Dockerfile
File Changed : 
1. Dockerfile : update docker file
> update docker file path

- Promact.Oauth.Server/src/Promact.Oauth.Server/Repository/ProjectsRepository/ProjectRepository.cs
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/project/project-add/project-add.html
- Promact.Oauth.Server/src/Promact.Oauth.Server/wwwroot/app/users/user-add/user-add.html
Fixes #333  and #335 
**Files changed are:**
**1. ProjectRepository.cs** - IsActive bit set to true.
**2. project-add.html** - Status check box removed.
**3. user-add.html** - Pattern for email added.
> Removed status check box from Add project and removed unnecessary validation from Add User

- Dockerfile
- Promact.Oauth.Server/src/Promact.Oauth.Server/gulpfile.js
- Promact.Oauth.Server/src/Promact.Oauth.Server/package.json
**Fixes** - build issue
**File Changed :**
**1. gulpfile.js** - removed rollup task
**2. package.json** - added rollup from npm command
**3. Dockerfile** - rearrange the command sequence of npm run
> Fixes build issue

- entrypoint.sh
Fixing the docker container running issue
File Changes:
entrypoint.sh
> fixed docker entrypoint issue
